markdown: kramdown
highlighter: rouge

# category archive
category_title_prefix: カテゴリー：
category_title_suffix: ' '
category_dir: category

sass:
    sass_dir: /assets/css/imports


url: https://oekaki-hoho-ron.github.io/oekaki-hoho-ron
